# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90c160451f881a929079798d68f60572096d06ba294551fd6ed93439ee1a41b85c5b4b49ebcd1510e097cdc90cd98c915a930739d3eba88e17890550c4e3978

test:
  secret_key_base: 6a56c4ed9fe68b32e551a00e04392bb3cede72d845b689240d272df59a97cdebf506ea167c27b19001fa977f8e8901eb42e2b66c716bef46139e445cd51d30d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
